### PR TITLE
fix: root.file.path not found

### PR DESCRIPTION
**Pull request by Mara-Li**
Sorry for the format, it's automatically done by my vscode.…
I fix the last bug I found in latest obsidian version, aka root.file.path not found…

Also,  fixing icon for obsidian default icon & switch icon when moving on custom order

### CODE REVIEW

**Comment by looneyapache** [comment]
Could you kindly provide guidance on how I may download the updated versions of main.js and manifest.json? 

Thank you very much!

**Comment by Mara-Li** [comment]
Hello!
No problem. I just needs to fix the problem with files at the root that doesn't get ordered properly :>. TBH it's a little difficult to understand but I will success as always!

**Comment by looneyapache** [comment]
Thank you! However, I'm completely clueless on how to use it. All I know is how to copy the main and manifest files; everything else is alien to me. I hope I'll figure it out with Google as my best friend :)

**Comment by Mara-Li** [comment]
It takes me. Six.
Hours.
To make it properly work.

*crying*

Should works in 5.11.0
See my own release tab for the plugin

**Comment by Mara-Li** [comment]
closed in favor of the main PR in bartender repo

**Pull request closed without merging**
